name: Unit Test

on:  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 11 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: adopt
    - name: Run unit tests and assemble APKs
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleProdRelease testProdReleaseUnitTest
    - name: Check Output
      run: bash ./etc/CheckBuild/check-release.sh test
      
      # Only upload artifacts built on Linux
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.sha }}
        path: /home/runner/work/xDrip/xDrip/app/build/outputs/apk/prod/release/
